# Generated by Django 2.2 on 2021-02-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20210202_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='books',
            name='release_year',
        ),
    ]
