# Generated by Django 2.2 on 2021-02-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20210202_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image_link',
            field=models.URLField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='isbn',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
    ]
